// Code generated by golex. DO NOT EDIT.

// Copyright (c) 2011 CZ.NIC z.s.p.o. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"bufio"
	"fmt"
	"log"
	"modernc.org/golex/lex"
)

type lexer struct {
	*lex.Lexer
}

type yylexer struct {
	src     *bufio.Reader
	buf     []byte
	empty   bool
	current byte
	prev    byte
}

func newLexer(src *bufio.Reader) (y *yylexer) {
	y = &yylexer{src: src}
	y.buf = make([]byte, 0)
	y.empty = false
	y.prev = 0
	if b, err := src.ReadByte(); err == nil {
		y.current = b
	}
	return
}

func (y *yylexer) getc() byte {
	y.prev = y.current
	if y.current != 0 {
		y.buf = append(y.buf, y.current)
	}
	y.current = 0
	if b, err := y.src.ReadByte(); err == nil {
		y.current = b
	}
	return y.current
}

func (y yylexer) Error(e string) {
	log.Fatal(e)
}

func (y *yylexer) Lex(lval *yySymType) int {
	//log.Println("get next sym")
	c := y.current
	if y.empty {
		c, y.empty = y.getc(), false
	}

yystate0:

	y.buf = y.buf[:0]

	switch yyt, yyb := 0, (y.prev == 0 || y.prev == '\n'); yyt {
	default:
		panic(fmt.Errorf(`invalid start condition %d`, yyt))
	case 0: // start condition: INITIAL
		if yyb {
			goto yystart176
		}
		goto yystart1
	}

yystate1:
	c = y.getc()
yystart1:
	switch {
	default:
		goto yystate3 // c >= '\x01' && c <= '\b' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '\x1f' || c == '!' || c >= '#' && c <= '&' || c == '*' || c == '+' || c >= ':' && c <= '<' || c >= '>' && c <= '@' || c == '[' || c == ']' || c == '^' || c == '`' || c >= '{' && c <= 'ÿ'
	case c == '"':
		goto yystate6
	case c == '(':
		goto yystate12
	case c == ')':
		goto yystate13
	case c == ',':
		goto yystate14
	case c == '-':
		goto yystate15
	case c == '.':
		goto yystate39
	case c == '/':
		goto yystate40
	case c == '=':
		goto yystate52
	case c == 'F':
		goto yystate54
	case c == 'N':
		goto yystate59
	case c == 'O':
		goto yystate65
	case c == '\'':
		goto yystate9
	case c == '\\':
		goto yystate68
	case c == '\n':
		goto yystate5
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate4
	case c == '\x00':
		goto yystate2
	case c == '_':
		goto yystate69
	case c == 'b':
		goto yystate75
	case c == 'c':
		goto yystate88
	case c == 'd':
		goto yystate98
	case c == 'i':
		goto yystate105
	case c == 'o':
		goto yystate118
	case c == 'r':
		goto yystate123
	case c == 's':
		goto yystate134
	case c == 't':
		goto yystate149
	case c == 'u':
		goto yystate154
	case c == 'w':
		goto yystate164
	case c >= '0' && c <= '9':
		goto yystate45
	case c >= 'A' && c <= 'E' || c >= 'G' && c <= 'M' || c >= 'P' && c <= 'Z' || c == 'a' || c >= 'e' && c <= 'h' || c >= 'j' && c <= 'n' || c == 'p' || c == 'q' || c == 'v' || c >= 'x' && c <= 'z':
		goto yystate53
	}

yystate2:
	c = y.getc()
	goto yyrule1

yystate3:
	c = y.getc()
	goto yyrule38

yystate4:
	c = y.getc()
	switch {
	default:
		goto yyrule3
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate5
	}

yystate5:
	c = y.getc()
	switch {
	default:
		goto yyrule3
	case c == '\t' || c == '\n' || c == '\r' || c == ' ':
		goto yystate5
	}

yystate6:
	c = y.getc()
	switch {
	default:
		goto yyrule38
	case c == '"':
		goto yystate8
	case c >= '\x01' && c <= '!' || c >= '#' && c <= 'ÿ':
		goto yystate7
	}

yystate7:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == '"':
		goto yystate8
	case c >= '\x01' && c <= '!' || c >= '#' && c <= 'ÿ':
		goto yystate7
	}

yystate8:
	c = y.getc()
	goto yyrule33

yystate9:
	c = y.getc()
	switch {
	default:
		goto yyrule38
	case c == '\'':
		goto yystate11
	case c >= '\x01' && c <= '&' || c >= '(' && c <= 'ÿ':
		goto yystate10
	}

yystate10:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == '\'':
		goto yystate11
	case c >= '\x01' && c <= '&' || c >= '(' && c <= 'ÿ':
		goto yystate10
	}

yystate11:
	c = y.getc()
	goto yyrule34

yystate12:
	c = y.getc()
	goto yyrule18

yystate13:
	c = y.getc()
	goto yyrule19

yystate14:
	c = y.getc()
	goto yyrule16

yystate15:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate16
	case c == '.':
		goto yystate20
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9':
		goto yystate25
	}

yystate16:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-' || c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate16
	case c == '\\':
		goto yystate17
	}

yystate17:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate18
	}

yystate18:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate19
	}

yystate19:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate16
	}

yystate20:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate21
	}

yystate21:
	c = y.getc()
	switch {
	default:
		goto yyrule36
	case c == 'E' || c == 'e':
		goto yystate22
	case c >= '0' && c <= '9':
		goto yystate21
	}

yystate22:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == '+' || c == '-':
		goto yystate23
	case c >= '0' && c <= '9':
		goto yystate24
	}

yystate23:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate24
	}

yystate24:
	c = y.getc()
	switch {
	default:
		goto yyrule36
	case c >= '0' && c <= '9':
		goto yystate24
	}

yystate25:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate16
	case c == '.':
		goto yystate26
	case c == 'E' || c == 'e':
		goto yystate34
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9':
		goto yystate25
	}

yystate26:
	c = y.getc()
	switch {
	default:
		goto yyrule35
	case c == 'E' || c == 'e':
		goto yystate31
	case c >= '0' && c <= '9':
		goto yystate27
	}

yystate27:
	c = y.getc()
	switch {
	default:
		goto yyrule35
	case c == 'E' || c == 'e':
		goto yystate28
	case c >= '0' && c <= '9':
		goto yystate27
	}

yystate28:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == '+' || c == '-':
		goto yystate29
	case c >= '0' && c <= '9':
		goto yystate30
	}

yystate29:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate30
	}

yystate30:
	c = y.getc()
	switch {
	default:
		goto yyrule35
	case c >= '0' && c <= '9':
		goto yystate30
	}

yystate31:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == '+' || c == '-':
		goto yystate32
	case c >= '0' && c <= '9':
		goto yystate33
	}

yystate32:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate33
	}

yystate33:
	c = y.getc()
	switch {
	default:
		goto yyrule35
	case c >= '0' && c <= '9':
		goto yystate33
	}

yystate34:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '+':
		goto yystate35
	case c == '-':
		goto yystate37
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9':
		goto yystate38
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate16
	}

yystate35:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c >= '0' && c <= '9':
		goto yystate36
	}

yystate36:
	c = y.getc()
	switch {
	default:
		goto yyrule37
	case c >= '0' && c <= '9':
		goto yystate36
	}

yystate37:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate16
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9':
		goto yystate38
	}

yystate38:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate16
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9':
		goto yystate38
	}

yystate39:
	c = y.getc()
	switch {
	default:
		goto yyrule38
	case c >= '0' && c <= '9':
		goto yystate21
	}

yystate40:
	c = y.getc()
	switch {
	default:
		goto yyrule38
	case c == '*':
		goto yystate41
	case c == '/':
		goto yystate44
	}

yystate41:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == '*':
		goto yystate42
	case c >= '\x01' && c <= ')' || c >= '+' && c <= 'ÿ':
		goto yystate41
	}

yystate42:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == '*':
		goto yystate42
	case c == '/':
		goto yystate43
	case c >= '\x01' && c <= ')' || c >= '+' && c <= '.' || c >= '0' && c <= 'ÿ':
		goto yystate41
	}

yystate43:
	c = y.getc()
	goto yyrule5

yystate44:
	c = y.getc()
	switch {
	default:
		goto yyrule4
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate44
	}

yystate45:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '.':
		goto yystate26
	case c == 'E' || c == 'e':
		goto yystate50
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9':
		goto yystate46
	case c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate46:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '.':
		goto yystate26
	case c == 'E' || c == 'e':
		goto yystate50
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9':
		goto yystate46
	case c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate47:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate48:
	c = y.getc()
	switch {
	default:
		goto yyabort
	case c == ']':
		goto yystate49
	case c >= '0' && c <= '9':
		goto yystate48
	}

yystate49:
	c = y.getc()
	goto yyrule31

yystate50:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '+':
		goto yystate35
	case c == '-':
		goto yystate37
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9':
		goto yystate51
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate51:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9':
		goto yystate51
	case c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate52:
	c = y.getc()
	goto yyrule17

yystate53:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate54:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == 'O':
		goto yystate55
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'N' || c >= 'P' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate55:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == 'R':
		goto yystate56
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Q' || c >= 'S' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate56:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == 'C':
		goto yystate57
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c == 'A' || c == 'B' || c >= 'D' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate57:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == 'E':
		goto yystate58
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'D' || c >= 'F' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate58:
	c = y.getc()
	switch {
	default:
		goto yyrule28
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate59:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == 'O':
		goto yystate60
	case c == 'U':
		goto yystate62
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'N' || c >= 'P' && c <= 'T' || c >= 'V' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate60:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == 'T':
		goto yystate61
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'S' || c >= 'U' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate61:
	c = y.getc()
	switch {
	default:
		goto yyrule29
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate62:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == 'L':
		goto yystate63
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'K' || c >= 'M' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate63:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == 'L':
		goto yystate64
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'K' || c >= 'M' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate64:
	c = y.getc()
	switch {
	default:
		goto yyrule30
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate65:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == 'I':
		goto yystate66
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'H' || c >= 'J' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate66:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == 'D':
		goto yystate67
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'C' || c >= 'E' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate67:
	c = y.getc()
	switch {
	default:
		goto yyrule9
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate68:
	c = y.getc()
	switch {
	default:
		goto yyrule38
	case c >= '0' && c <= '9':
		goto yystate18
	}

yystate69:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'n':
		goto yystate70
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate47
	}

yystate70:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'u':
		goto yystate71
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate47
	}

yystate71:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'l':
		goto yystate72
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate47
	}

yystate72:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'l':
		goto yystate73
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate47
	}

yystate73:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == '_':
		goto yystate74
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate74:
	c = y.getc()
	switch {
	default:
		goto yyrule14
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate75:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'o':
		goto yystate76
	case c == 'u':
		goto yystate84
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate47
	}

yystate76:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'o':
		goto yystate77
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate47
	}

yystate77:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 't':
		goto yystate78
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate47
	}

yystate78:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 's':
		goto yystate79
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z':
		goto yystate47
	}

yystate79:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 't':
		goto yystate80
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate47
	}

yystate80:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'r':
		goto yystate81
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate47
	}

yystate81:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'a':
		goto yystate82
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate47
	}

yystate82:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'p':
		goto yystate83
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z':
		goto yystate47
	}

yystate83:
	c = y.getc()
	switch {
	default:
		goto yyrule10
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate84:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'i':
		goto yystate85
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate47
	}

yystate85:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'l':
		goto yystate86
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate47
	}

yystate86:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'd':
		goto yystate87
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z':
		goto yystate47
	}

yystate87:
	c = y.getc()
	switch {
	default:
		goto yyrule21
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate88:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'l':
		goto yystate89
	case c == 'r':
		goto yystate93
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate47
	}

yystate89:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'o':
		goto yystate90
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate47
	}

yystate90:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 's':
		goto yystate91
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z':
		goto yystate47
	}

yystate91:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate92
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate92:
	c = y.getc()
	switch {
	default:
		goto yyrule7
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate93:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate94
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate94:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'a':
		goto yystate95
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate47
	}

yystate95:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 't':
		goto yystate96
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate47
	}

yystate96:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate97
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate97:
	c = y.getc()
	switch {
	default:
		goto yyrule8
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate98:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate99
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate99:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'c':
		goto yystate100
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z':
		goto yystate47
	}

yystate100:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'l':
		goto yystate101
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate47
	}

yystate101:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'a':
		goto yystate102
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate47
	}

yystate102:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'r':
		goto yystate103
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate47
	}

yystate103:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate104
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate104:
	c = y.getc()
	switch {
	default:
		goto yyrule20
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate105:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'n':
		goto yystate106
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate47
	}

yystate106:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'd':
		goto yystate107
	case c == 's':
		goto yystate114
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'r' || c >= 't' && c <= 'z':
		goto yystate47
	}

yystate107:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate108
	case c == 'i':
		goto yystate110
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate47
	}

yystate108:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'x':
		goto yystate109
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'w' || c == 'y' || c == 'z':
		goto yystate47
	}

yystate109:
	c = y.getc()
	switch {
	default:
		goto yyrule24
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate110:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'c':
		goto yystate111
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c == 'a' || c == 'b' || c >= 'd' && c <= 'z':
		goto yystate47
	}

yystate111:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate112
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate112:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 's':
		goto yystate113
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z':
		goto yystate47
	}

yystate113:
	c = y.getc()
	switch {
	default:
		goto yyrule22
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate114:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate115
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate115:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'r':
		goto yystate116
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate47
	}

yystate116:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 't':
		goto yystate117
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate47
	}

yystate117:
	c = y.getc()
	switch {
	default:
		goto yyrule15
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate118:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'n':
		goto yystate119
	case c == 'p':
		goto yystate120
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c == 'o' || c >= 'q' && c <= 'z':
		goto yystate47
	}

yystate119:
	c = y.getc()
	switch {
	default:
		goto yyrule25
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate120:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate121
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate121:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'n':
		goto yystate122
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate47
	}

yystate122:
	c = y.getc()
	switch {
	default:
		goto yyrule6
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate123:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'o':
		goto yystate124
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate47
	}

yystate124:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'w':
		goto yystate125
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'v' || c >= 'x' && c <= 'z':
		goto yystate47
	}

yystate125:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 't':
		goto yystate126
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate47
	}

yystate126:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'y':
		goto yystate127
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'x' || c == 'z':
		goto yystate47
	}

yystate127:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'p':
		goto yystate128
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'o' || c >= 'q' && c <= 'z':
		goto yystate47
	}

yystate128:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate129
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate129:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == '_':
		goto yystate130
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate130:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'o':
		goto yystate131
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate47
	}

yystate131:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'i':
		goto yystate132
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate47
	}

yystate132:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'd':
		goto yystate133
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z':
		goto yystate47
	}

yystate133:
	c = y.getc()
	switch {
	default:
		goto yyrule13
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate134:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'h':
		goto yystate135
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'g' || c >= 'i' && c <= 'z':
		goto yystate47
	}

yystate135:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'a':
		goto yystate136
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate47
	}

yystate136:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'r':
		goto yystate137
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate47
	}

yystate137:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate138
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate138:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'd':
		goto yystate139
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z':
		goto yystate47
	}

yystate139:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == '_':
		goto yystate140
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate140:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'r':
		goto yystate141
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'q' || c >= 's' && c <= 'z':
		goto yystate47
	}

yystate141:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate142
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate142:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'l':
		goto yystate143
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'k' || c >= 'm' && c <= 'z':
		goto yystate47
	}

yystate143:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'a':
		goto yystate144
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate47
	}

yystate144:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 't':
		goto yystate145
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate47
	}

yystate145:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'i':
		goto yystate146
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate47
	}

yystate146:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'o':
		goto yystate147
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate47
	}

yystate147:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'n':
		goto yystate148
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate47
	}

yystate148:
	c = y.getc()
	switch {
	default:
		goto yyrule11
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate149:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'o':
		goto yystate150
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate47
	}

yystate150:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'a':
		goto yystate151
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'b' && c <= 'z':
		goto yystate47
	}

yystate151:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 's':
		goto yystate152
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z':
		goto yystate47
	}

yystate152:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 't':
		goto yystate153
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate47
	}

yystate153:
	c = y.getc()
	switch {
	default:
		goto yyrule27
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate154:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'n':
		goto yystate155
	case c == 's':
		goto yystate160
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'r' || c >= 't' && c <= 'z':
		goto yystate47
	}

yystate155:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'i':
		goto yystate156
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate47
	}

yystate156:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'q':
		goto yystate157
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'p' || c >= 'r' && c <= 'z':
		goto yystate47
	}

yystate157:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'u':
		goto yystate158
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate47
	}

yystate158:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'e':
		goto yystate159
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'd' || c >= 'f' && c <= 'z':
		goto yystate47
	}

yystate159:
	c = y.getc()
	switch {
	default:
		goto yyrule23
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate160:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'i':
		goto yystate161
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate47
	}

yystate161:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'n':
		goto yystate162
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'm' || c >= 'o' && c <= 'z':
		goto yystate47
	}

yystate162:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'g':
		goto yystate163
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'f' || c >= 'h' && c <= 'z':
		goto yystate47
	}

yystate163:
	c = y.getc()
	switch {
	default:
		goto yyrule26
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate164:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'i':
		goto yystate165
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate47
	}

yystate165:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 't':
		goto yystate166
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate47
	}

yystate166:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'h':
		goto yystate167
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'g' || c >= 'i' && c <= 'z':
		goto yystate47
	}

yystate167:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'o':
		goto yystate168
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate47
	}

yystate168:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'u':
		goto yystate169
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 't' || c >= 'v' && c <= 'z':
		goto yystate47
	}

yystate169:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 't':
		goto yystate170
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 's' || c >= 'u' && c <= 'z':
		goto yystate47
	}

yystate170:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == '_':
		goto yystate171
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate171:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'o':
		goto yystate172
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'n' || c >= 'p' && c <= 'z':
		goto yystate47
	}

yystate172:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'i':
		goto yystate173
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'h' || c >= 'j' && c <= 'z':
		goto yystate47
	}

yystate173:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 'd':
		goto yystate174
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'c' || c >= 'e' && c <= 'z':
		goto yystate47
	}

yystate174:
	c = y.getc()
	switch {
	default:
		goto yyrule32
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c == 's':
		goto yystate175
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'r' || c >= 't' && c <= 'z':
		goto yystate47
	}

yystate175:
	c = y.getc()
	switch {
	default:
		goto yyrule12
	case c == '-':
		goto yystate16
	case c == '[':
		goto yystate48
	case c == '\\':
		goto yystate17
	case c >= '0' && c <= '9' || c >= 'A' && c <= 'Z' || c == '_' || c >= 'a' && c <= 'z':
		goto yystate47
	}

yystate176:
	c = y.getc()
yystart176:
	switch {
	default:
		goto yystate3 // c >= '\x01' && c <= '\b' || c == '\v' || c == '\f' || c >= '\x0e' && c <= '\x1f' || c == '!' || c >= '$' && c <= '&' || c == '*' || c == '+' || c >= ':' && c <= '<' || c >= '>' && c <= '@' || c == '[' || c == ']' || c == '^' || c == '`' || c >= '{' && c <= 'ÿ'
	case c == '"':
		goto yystate6
	case c == '#':
		goto yystate177
	case c == '(':
		goto yystate12
	case c == ')':
		goto yystate13
	case c == ',':
		goto yystate14
	case c == '-':
		goto yystate15
	case c == '.':
		goto yystate39
	case c == '/':
		goto yystate40
	case c == '=':
		goto yystate52
	case c == 'F':
		goto yystate54
	case c == 'N':
		goto yystate59
	case c == 'O':
		goto yystate65
	case c == '\'':
		goto yystate9
	case c == '\\':
		goto yystate68
	case c == '\n':
		goto yystate5
	case c == '\t' || c == '\r' || c == ' ':
		goto yystate4
	case c == '\x00':
		goto yystate2
	case c == '_':
		goto yystate69
	case c == 'b':
		goto yystate75
	case c == 'c':
		goto yystate88
	case c == 'd':
		goto yystate98
	case c == 'i':
		goto yystate105
	case c == 'o':
		goto yystate118
	case c == 'r':
		goto yystate123
	case c == 's':
		goto yystate134
	case c == 't':
		goto yystate149
	case c == 'u':
		goto yystate154
	case c == 'w':
		goto yystate164
	case c >= '0' && c <= '9':
		goto yystate45
	case c >= 'A' && c <= 'E' || c >= 'G' && c <= 'M' || c >= 'P' && c <= 'Z' || c == 'a' || c >= 'e' && c <= 'h' || c >= 'j' && c <= 'n' || c == 'p' || c == 'q' || c == 'v' || c >= 'x' && c <= 'z':
		goto yystate53
	}

yystate177:
	c = y.getc()
	switch {
	default:
		goto yyrule2
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate178
	}

yystate178:
	c = y.getc()
	switch {
	default:
		goto yyrule2
	case c >= '\x01' && c <= '\t' || c >= '\v' && c <= 'ÿ':
		goto yystate178
	}

yyrule1: // \0
	{
		return 0
	}
yyrule2: // ^#[^\n]*
	{
		{
			log.Println("pass comments", string(y.buf), string(y.current))
		}
		goto yystate0
	}
yyrule3: // [ \t\n\r]+
yyrule4: // \/\/.*
yyrule5: // \/\*([^*]|\*+[^*/])*\*+\/

	goto yystate0
yyrule6: // open
	{
		lval.str = string(y.buf)
		return OPEN
		goto yystate0
	}
yyrule7: // close
	{
		lval.str = string(y.buf)
		return XCLOSE
		goto yystate0
	}
yyrule8: // create
	{
		{
			log.Println("create something")
			lval.str = string(y.buf)
			return XCREATE
		}
		goto yystate0
	}
yyrule9: // OID
	{
		lval.str = string(y.buf)
		return OBJ_ID
		goto yystate0
	}
yyrule10: // bootstrap
	{
		lval.str = string(y.buf)
		return XBOOTSTRAP
		goto yystate0
	}
yyrule11: // "shared_relation"
	{
		lval.str = string(y.buf)
		return XSHARED_RELATION
		goto yystate0
	}
yyrule12: // "without_oids"
	{
		lval.str = string(y.buf)
		return XWITHOUT_OIDS
		goto yystate0
	}
yyrule13: // "rowtype_oid"
	{
		lval.str = string(y.buf)
		return XROWTYPE_OID
		goto yystate0
	}
yyrule14: // _null_
	{
		lval.str = string(y.buf)
		return NULLVAL
		goto yystate0
	}
yyrule15: // insert
	{
		lval.str = string(y.buf)
		return INSERT_TUPLE
		goto yystate0
	}
yyrule16: // ","
	{
		return COMMA
	}
yyrule17: // "="
	{
		return EQUALS
	}
yyrule18: // "("
	{
		return LPAREN
	}
yyrule19: // ")"
	{
		return RPAREN
	}
yyrule20: // "declare"
	{
		lval.str = string(y.buf)
		return XDECLARE
		goto yystate0
	}
yyrule21: // "build"
	{
		lval.str = string(y.buf)
		return XBUILD
		goto yystate0
	}
yyrule22: // "indices"
	{
		lval.str = string(y.buf)
		return INDICES
		goto yystate0
	}
yyrule23: // "unique"
	{
		lval.str = string(y.buf)
		return UNIQUE
		goto yystate0
	}
yyrule24: // "index"
	{
		lval.str = string(y.buf)
		return INDEX
		goto yystate0
	}
yyrule25: // "on"
	{
		lval.str = string(y.buf)
		return ON
		goto yystate0
	}
yyrule26: // "using"
	{
		lval.str = string(y.buf)
		return USING
		goto yystate0
	}
yyrule27: // "toast"
	{
		lval.str = string(y.buf)
		return XTOAST
		goto yystate0
	}
yyrule28: // "FORCE"
	{
		lval.str = string(y.buf)
		return XFORCE
		goto yystate0
	}
yyrule29: // "NOT"
	{
		lval.str = string(y.buf)
		return XNOT
		goto yystate0
	}
yyrule30: // "NULL"
	{
		lval.str = string(y.buf)
		return XNULL
		goto yystate0
	}
yyrule31: // {arrayid}
	{
		{
			lval.str = string(y.buf)
			return ID
		}
		goto yystate0
	}
yyrule32: // {id}
	{
		{
			lval.str = string(y.buf)
			//log.Println("id", string(y.buf));
			return ID
		}
		goto yystate0
	}
yyrule33: // {sid}
	{
		{
			lval.str = string(y.buf)
			return ID
		}
		goto yystate0
	}
yyrule34: // {sid2}
	{
		{
			lval.str = string(y.buf)
			return ID
		}
		goto yystate0
	}
yyrule35: // (-)?{D}+"."{D}*({Exp})?
yyrule36: // (-)?{D}*"."{D}+({Exp})?
yyrule37: // (-)?{D}+{Exp}
	{
		{
			lval.str = string(y.buf)
			log.Println("const", string(y.buf))
			return CONST_P
		}
		goto yystate0
	}
yyrule38: // .
	if true { // avoid go vet determining the below panic will not be reached
		{
			log.Println("syntax error?", string(y.buf), string(y.current))
			fmt.Printf("%q\n", y.buf)
		}
		goto yystate0
	}
	panic("unreachable")

yyabort: // no lexem recognized
	//
	// silence unused label errors for build and satisfy go vet reachability analysis
	//
	{
		if false {
			goto yyabort
		}
		if false {
			goto yystate0
		}
		if false {
			goto yystate1
		}
		if false {
			goto yystate176
		}
	}

	{
		log.Println("end syntax error?", string(y.buf), string(y.current))
	}
	log.Fatal("scanner internal error")
	y.empty = true
	return NOTHING
}
