#
#
# src/backend/new_executor/arrow/Makefile
#

subdir = src/backend/sdb/arrow
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = array_builder.o  array_to_scalar_exchanger.o  boot.o  data_type_helper.o  recordbatch_builder.o  recordbatch_to_slot_exchanger.o

include $(top_srcdir)/src/backend/common.mk
