#
#
# src/backend/new_executor/arrow/Makefile
#

subdir = src/backend/new_executor/arrow
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = column_builder.o column_exchanger.o recordbatch_builder.o recordbatch_exchanger.o type_mapping.o

include $(top_srcdir)/src/backend/common.mk
