#
#
# src/backend/new_executor/Makefile
#

subdir = src/backend/new_executor
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS =

SUBDIRS	= arrow

include $(top_srcdir)/src/backend/common.mk
